// Generated by CoffeeScript 1.3.3
(function() {
  var Neon;

  Neon = require('../javascripts/neon/neon.js').Neon;

  global['Class'] = Neon.Class;

  global['Module'] = Neon.Class;

  require('../javascripts/neon/customEvent.js');

  require('../javascripts/neon/customEventSupport.js');

  require('../javascripts/utils/color.js');

  global['Karma'] = {};

  require('../js_source/karma/chameleon');

  require('../js_source/karma/rule');

  require('../js_source/karma/colorPicker');

  require('../javascripts/tellurium/tellurium.js');

  Tellurium.suite('Karma.Chameleon')(function() {
    return this.describe('Creating an initial rule')(function() {
      return this.specify('It should have a baseRule property')(function() {
        var chameleon;
        chameleon = new Karma.Chameleon();
        this.assert(chameleon.baseRule).not().toBe(null);
        return this.completed();
      });
    });
  });

  Tellurium.run();

}).call(this);
